name: jizt
description: Jizt app.

publish_to: 'none'

version: 0.3.0+0 # Build number set by CICD system

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: modules/domain
  jizt_repository:
    path: modules/data/jizt_repository
  flutter_bloc: ^7.0.0                # https://pub.dev/packages/flutter_bloc
  rxdart: ^0.26.0                     # https://pub.dev/packages/rxdart
  equatable: ^2.0.0                   # https://pub.dev/packages/equatable
  flutter_svg: ^0.21.0-nullsafety.0   # https://pub.dev/packages/flutter_svg
  expandable: ^5.0.1                  # https://pub.dev/packages/expandable
  share: ^2.0.1                       # https://pub.dev/packages/share
  clipboard: ^0.1.3                   # https://pub.dev/packages/clipboard
  fluttertoast: ^8.0.3                # https://pub.dev/packages/fluttertoast
  timeago: ^3.0.2                     # https://pub.dev/packages/timeago
  intl: ^0.17.0                       # https://pub.dev/packages/intl

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^8.0.0                   # https://pub.dev/packages/bloc_test

flutter:
  uses-material-design: true

  assets:
    - assets/drawables/
  fonts:
    - family: Varela
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
