name: Test build
on:
  push:
    branches:
      - '*'
      - '!wip/**'

jobs:
  test:
    name: Test build
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2 # https://github.com/subosito/flutter-action
        with:
          channel: 'stable'

      - name: Enable flutter web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --no-pub --test-randomize-ordering-seed random
